baseurl = "https://kenan-rhoton.github.io"
languageCode = "en-us"
title = "One True Way"
theme = "hugo-steam-theme"
disqusShortname = ""
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 10

[params]
	title = "One True Way"
	subtitle = "The different approaches to development"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor = "orange"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Kenan Rhoton"
	bio = "programmer - blogger"
	description = "A blog where we discuss the Way of doing things"
	
	# Link your social networks (optional)
	location = ""
	twitter = ""
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "kenan-rhoton"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
